cargo-features = ["edition2021"]
[package]
name = "ff6recompress"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.apultra]
path = "apultra-rs"
