brace_style="AlwaysNextLine"
condense_wildcard_suffixes=true
control_brace_style="AlwaysNextLine"
edition = "2021"
enum_discrim_align_threshold=50
format_code_in_doc_comments=true
format_macro_matchers=true
group_imports="StdExternalCrate"
imports_granularity="Crate"
match_arm_leading_pipes = "Always"
match_block_trailing_comma=true
newline_style = "unix"
reorder_impl_items=true
report_fixme="Always"
report_todo="Always"
struct_field_align_threshold=50
unstable_features=true
use_field_init_shorthand = true
use_small_heuristics="Max"
use_try_shorthand = true
version = "Two"
where_single_line=true
